<?php
/**
 * @file
 * Module file.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function feedback_simple_theme($existing, $type, $theme, $path) {
  global $base_url;
  $variables = \Drupal::configFactory()->getEditable('feedback_simple.settings')->get("feedback_simple");
  $image_url = \Drupal::moduleHandler()->getModule('feedback_simple')->getPath() . "/image/feedback_simple.gif";
  $image = Drupal::service('image.factory')->get($base_url. "/".$image_url);
  $width = $image->getWidth();
  $height = $image->getHeight();
  $variables['image'] = $base_url. "/".$image_url;
  \Drupal::configFactory()->getEditable('feedback_simple.settings')->set("feedback_simple", $variables);

  $registry['feedback_simple'] = array(
    'variables' => array(
      'enabled' => $variables['enabled'],
      'link' => $variables['link'],
      'target' => $variables['target'],
      'class' => $variables['class'],
      'align' => $variables['align'],
      'top' => $variables['top'],
      'image' => $variables['image'],
      'alt' => $variables['alt'],
      'deny' => $variables['deny'],
      'allow' => $variables['allow'],
      // Computed from image.
      'height' => $height,
      'width' => $width,
    ),
  );

  return $registry;
}

function feedback_simple_page_bottom(array &$page_bottom) {
  $page_bottom['feedback_simple'] = [
    '#theme' => 'feedback_simple'
  ];
}


/**
 * Implements hook_preprocess_feedback_simple().
 */
function feedback_simple_preprocess_feedback_simple(&$variables) {

  // Hide the tab when on the $link page.
  if (Url::fromRoute("<current>")->toString() == $variables['link']) {
    $variables['enabled'] = FALSE;
  }

  // Deny and allow rules.
  if (\Drupal::service('path.matcher')->matchPath(Url::fromRoute("<current>")->toString(), $variables['deny'])) {
    $variables['enabled'] = FALSE;
  }
  if (\Drupal::service('path.matcher')->matchPath(Url::fromRoute("<current>")->toString(), $variables['allow'])) {
    $variables['enabled'] = TRUE;
  }
}

/**
 * Implements hook_page_attachments().
 */
function feedback_simple_page_attachments(&$page) {
  $page['#attached']['library'][] = 'feedback_simple/feedback_simple';
}

